# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/docker_data_analysis',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/docker_data_analysis',
                'lib_path': 'docker_data_analysis'},
  'syms': {}}
